apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "self.name" . }}-nginx-{{ .Release.Name }}
  labels:
    {{- include "self.common-labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas | default 2 }}
  selector:
    matchLabels:
      {{- include "self.match-selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "self.match-selector" . | nindent 8 }}
    spec:
        containers:
          - name: nginx
            image: nginx:1.14.2
            ports:
            - containerPort: 80