apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: liveness
  name: liveness
  namespace: probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness
  template:
    metadata:
      labels:
        app: liveness
    spec:
      containers:
        - image: nginx
          name: liveness
          command:
            - sh
            - -c
            # kill nginx after 25 seconds to simulate an exception in the application
            - ( timeout 25 nginx -g "daemon off;" ); echo "Exception occurred!"; exec sleep infinity
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: liveness
  name: liveness
  namespace: probes
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: liveness
  type: ClusterIP
