apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - nodea
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Mi
  local:
    path: ./local-storage
