apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: lab-kustomize-dev

commonLabels:
  env: dev

configMapGenerator:
  - name: my-config
    literals:
      - msg=Hello world!
      - env=dev

patches:
  - path: replicas.yaml
