apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resource-management-cpu
  name: resource-management-cpu
  namespace: resource-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-management-cpu
  template:
    metadata:
      labels:
        app: resource-management-cpu
    spec:
      containers:
        - command:
            - "cat"
            - "/dev/zero"
            - ">"
            - "/dev/null"
          image: busybox
          name: resource-management-cpu
          resources:
            requests:
              memory: "30M"
              cpu: "50m"
            limits:
              memory: "40M"
              cpu: "100m"