apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resource-management-oom
  name: resource-management-oom
  namespace: resource-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-management-oom
  template:
    metadata:
      labels:
        app: resource-management-oom
    spec:
      containers:
        - command:
            - "eatmemory"
            - "50M"
          image: julman99/eatmemory
          name: resource-management-oom
          resources:
            requests:
              memory: "30M"
              cpu: "50m"
            limits:
              memory: "40M"
              cpu: "100m"